### ISSUE TITLE
Error with unpublished pages when using Re-generate task

### ISSUE THREAD

**Issue by jellygnite** [SilverStripers/elemental-seach#11]
When using the 'Re-generate all search documents' task all pages are added to the SearchDocument table regardless of published status. This then throws an error on the search results page due to a null object.

I think there needs to be a check in the task to see if object is versioned and if so then only use Live version.

**Comment by fonsekaean** [comment]
Thanks for reporting that. We will check it and let you know.

**Comment by fonsekaean** [comment]
@Jellygnite this is sorted on the dev-master now.
