### ISSUE TITLE
Error when building database

### ISSUE THREAD

**Issue by peterkoopman** [SilverStripers/elemental-seach#17]
I run /dev/build?flush after installing and get an error:
`[Emergency] Uncaught SilverStripe\ORM\Connect\DatabaseException: Couldn't run query: ALTER TABLE "File" DROP INDEX "SearchFields", ADD fulltext "SearchFields" ("Name","Title","Name","Title") 42S21-1060: Duplicate column name 'Name'`

**Comment by fonsekaean** [comment]
Hello @peterkoopman Can you check whether you have `FulltextSearchable::enable();` in your app/_config.php and if you find it remove that and give it a go.

**Comment by quamsta** [comment]
I'm also having this exact same issue/error message, FulltextSearchable is enabled. It looks like the dev/build schema code is trying to add a "Name" column to the "File" table which already contains that column..

**Comment by quamsta** [comment]
Oops! I misread, I thought we needed to enable the default FullTextSearchable not **remove** it. After removing FulltextSearchable::enable(); in my app's config, dev/build completes properly. Thanks!!

**Comment by fonsekaean** [comment]
@quamsta yeah, its a bit confusing isnt it ?
