### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by abstractk** [SilverStripers/elemental-seach#3]
Hey!

Is this still maintained? If yes, any plans to support `"dnadesign/silverstripe-elemental": "^4"` ?

**Comment by fonsekaean** [comment]
Hello @abstractk 

Well yes, but we havent had a chance to use it on elemental 4 yet. But surely if you have time please send a merge request. Right now I dont see that I will have enough time to update this for the next couple of weeks.

**Comment by abstractk** [comment]
Thanks! I'll test this with elemental 4 and send a PR.
